package com.imsdk.imdeveloper.bean;

public class CommunityEvent {
    private String id;

    private String title;
    public void setTitle(String title) {
        this.title = title;
    }


    public String getTitle() {
        return title;
    }

    private String communityid;

    
    private String eventcontent;

   
    private String date;

   
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityevent.CommunityID
     *
     * @return the value of t_communityevent.CommunityID
     *
     * @mbggenerated
     */
    public String getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityevent.CommunityID
     *
     * @param communityid the value for t_communityevent.CommunityID
     *
     * @mbggenerated
     */
    public void setCommunityid(String communityid) {
        this.communityid = communityid == null ? null : communityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityevent.EventContent
     *
     * @return the value of t_communityevent.EventContent
     *
     * @mbggenerated
     */
    public String getEventcontent() {
        return eventcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityevent.EventContent
     *
     * @param eventcontent the value for t_communityevent.EventContent
     *
     * @mbggenerated
     */
    public void setEventcontent(String eventcontent) {
        this.eventcontent = eventcontent == null ? null : eventcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityevent.Date
     *
     * @return the value of t_communityevent.Date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityevent.Date
     *
     * @param date the value for t_communityevent.Date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date;
    }
}