package com.imsdk.imdeveloper.bean;

public class Rlation {
    private String id;

    
    private String userid;

    
    private String communityid;

  
    private String position;

 
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rlation.ID
     *
     * @param id the value for t_rlation.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rlation.UserID
     *
     * @return the value of t_rlation.UserID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rlation.UserID
     *
     * @param userid the value for t_rlation.UserID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rlation.CommunityID
     *
     * @return the value of t_rlation.CommunityID
     *
     * @mbggenerated
     */
    public String getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rlation.CommunityID
     *
     * @param communityid the value for t_rlation.CommunityID
     *
     * @mbggenerated
     */
    public void setCommunityid(String communityid) {
        this.communityid = communityid == null ? null : communityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rlation.Position
     *
     * @return the value of t_rlation.Position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rlation.Position
     *
     * @param position the value for t_rlation.Position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}